#!/usr/bin/env bash
set -euo pipefail -o posix

cd "$(git rev-parse --show-toplevel)"

yarn install --dev --frozen-lockfile --silent

# This command will launch a Chromium browser for testing.
yarn run jest --config=./tests/jest.config.js --detectOpenHandles --passWithNoTests ./tests
